#pragma once

const char html_page[] PROGMEM = R"=====(
<!DOCTYPE html>
<html>
  <script>
    let contents=[],links=[],selectedIndex;async function fetchMainPage(){try{let e=await fetch("https://raw.githubusercontent.com/ehanover/lights-arduinowifi-sunrise/main/main.html");document.body.innerHTML=await e.text()}catch(t){console.log("Fetch error:"+t)}}function inputToRGB(e){let t=document.getElementById(e).value;return[parseInt(t.substr(1,2),16),parseInt(t.substr(3,2),16),parseInt(t.substr(5,2),16)]}function hueInputToByte(e){let t=document.getElementById(e).value;return Math.floor(255*(t/330))}function showTab(e){contents[selectedIndex].style.display="none",contents[e].style.display="flex",links[selectedIndex].classList.remove("tab-link-selected"),links[e].classList.add("tab-link-selected"),selectedIndex=e}function submit(){if(4==selectedIndex){let e=new Date,t=new Date(e.toISOString().split("T")[0]+"T"+document.getElementById("sunrise-time").value),n=Math.floor((t.getTime()-e.getTime())/1e3);n<0?n+=86400:n%=86400,console.log("seconds till:",n),postData([2,n>>>16&255,n>>>8&255,n>>>0&255].concat(inputToRGB("sunrise-color")).concat(document.getElementById("sunrise-duration").value))}else 1==selectedIndex?postData([3,hueInputToByte("swirl-hue-1"),hueInputToByte("swirl-hue-2"),hueInputToByte("swirl-hue-3"),document.getElementById("swirl-speed").value,document.getElementById("swirl-brightness").value]):0==selectedIndex?postData([4,document.getElementById("rave-value-rainbow").checked,document.getElementById("rave-speed").value,document.getElementById("rave-brightness").value]):2==selectedIndex?postData([5,document.getElementById("fireworks-speed").value,document.getElementById("fireworks-brightness").value]):3==selectedIndex&&postData([1].concat(inputToRGB("solid-color")))}function postData(e){let t=new Uint8Array(e);console.log("posting data:",t);let n=window.location.href;fetch(n,{method:"POST",body:t})}window.onload=async()=>{await fetchMainPage(),contents=document.getElementsByClassName("tab-content"),links=document.getElementsByClassName("tab-link");let e=document.getElementById("swirl-hue-1");e.addEventListener("input",()=>document.getElementById("swirl-hue-1-parent").style.backgroundColor=`hsl(${e.value}, 100%, 50%)`);let t=document.getElementById("swirl-hue-2");t.addEventListener("input",()=>document.getElementById("swirl-hue-2-parent").style.backgroundColor=`hsl(${t.value}, 100%, 50%)`);let n=document.getElementById("swirl-hue-3");n.addEventListener("input",()=>document.getElementById("swirl-hue-3-parent").style.backgroundColor=`hsl(${n.value}, 100%, 50%)`),selectedIndex=0,showTab(0)};
  </script>
</html>
)=====";
